name: Docker Image and Package CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/staubrein/lexbot:latest --tag ghcr.io/staubrein/lexbot:v12

    - name: Publish Docker image to Github Packages
      shell: bash
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        echo $PAT | docker login ghcr.io --username lexbot --password-stdin
        docker push ghcr.io/staubrein/lexbot:latest
        docker push ghcr.io/staubrein/lexbot:v12
        docker logout


